# Generated by Django 3.0.7 on 2021-07-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210714_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
